name: Deploy WebGL to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'build*.data.gz'
      - 'build*.framework.js'
      - 'build*.loader.js'
      - 'build*.wasm.gz'
      - 'TemplateData/**'
      - '*.mp4'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Build Folder
        run: |
          mkdir build_artifact
          cp index.html build_artifact
          cp build* build_artifact || true
          cp -r TemplateData build_artifact/TemplateData || true
          cp *.mp4 build_artifact || true
          cp *.png build_artifact || true
          cp *.ico build_artifact || true
          cp *.css build_artifact || true
          
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build_artifact
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
