name: Deploy WebGL to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**' 
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Build Folder
        run: |
          # 必要なファイルを直接指定してコピー
          mkdir build_artifact
          cp index.html build_artifact
          cp build2025110411041858.data.gz build_artifact || true
          cp build2025110411041858.framework.js build_artifact || true
          cp build2025110411041858.loader.js build_artifact || true
          cp build2025110411041858.wasm.gz build_artifact || true
          
          # その他必要なアセット類
          cp -r TemplateData build_artifact/TemplateData || true
          cp result1_re.mp4 build_artifact || true
          cp result2_re.mp4 build_artifact || true
          
          # その他、favicon.ico, pngファイルなどもコピー
          cp *.ico build_artifact || true
          cp *.png build_artifact || true
          cp style.css build_artifact || true
          
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build_artifact
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
